
name: Release Vscode Plugin
on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  npmInstall:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - name: Change dir
        run:
          ls
          
      - uses: actions/checkout@v2
      - run: npm install
          
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
