
name: Release Vscode Plugin
on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  npmInstall:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run:  npm install
      - name: Vscode release plugin
        run: npm install -g vsce
      - name: set vsce
        run: vsce login MRSlouu && ${{ secrets.PUBLISHER_TOKEN }}
      - name: package and publish
        run: vsce package && vsce publish
